# Generated by Django 4.1.7 on 2023-03-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
